Rascunho inicial
PosFiap/tech_challenge pull request #4
Opened 2023-06-30 02:13 UTC by lia-dias

2023-06-30 12:41 UTC, m-dantas approved these changes

2023-06-30 13:13 UTC, encortonado approved these changes

2023-07-02 20:29 UTC, sandroramone approved these changes

2023-07-03 23:49 UTC, merged

2023-07-03 23:51 UTC, sandroramone requested changes

2023-07-03 23:51 UTC, sandroramone commented on index.ts
uma mudança necessária que vi aqui seria esse arquivo index estar dentro da pasta src, qualquer código deixarmos sempre dentro dela pra que não fiquem de fora na hora que rodar os containers docker, assim teremos todos os códigos fontes dentro dessa pasta, caso achem necessário criar uma pasta pra armazenar esse código inicializador do processo ou fazer algo mais referente a ele podemos criar uma pasta ```main``` e colocar esses códigos dentro

2023-07-04 00:58 UTC, lia-dias commented on index.ts
Eu concordo. No próximo código que subir eu vou mover esse código. Podemos mesmo deixar na raiz do src, acho que não precisamos de uma pasta para um único arquivo.