Feat/orm
PosFiap/tech_challenge pull request #7
Opened 2023-07-01 17:38 UTC by m-dantas

2023-07-04 00:20 UTC, lia-dias requested changes
Está tudo certo. Considerei o foco do PR, o uso de ORM e uso do Prima nos Repositories. Só pontuei algumas coisas em relação ao mapeamento do relacionamento das entidades no database.

2023-07-04 00:20 UTC, lia-dias commented on prisma/migrations/20230630204300_init/migration.sql
> +    "cpf" TEXT,
Podemos usar o próprio CPF como chave aqui

2023-07-04 00:20 UTC, lia-dias commented on prisma/migrations/20230630204300_init/migration.sql
> +    "cpf_cliente" TEXT NOT NULL,
Um pedido não precisa ter um CPF, ele pode ser feito anonimamente, se lembram?

2023-07-04 00:20 UTC, lia-dias commented on prisma/migrations/20230630204300_init/migration.sql
> +    "cpf_cliente" TEXT NOT NULL,
No caso, me referindo ao 'NOT NULL'

2023-07-04 00:20 UTC, lia-dias commented on prisma/migrations/20230630204300_init/migration.sql
> +    "codigo" SERIAL NOT NULL,
Um ProdutoPedido não necessariamente precisa ter um código, acaba dificultando na hora de procurar pelo número do pedido ou pelo número do produto, fica melhor trabalhar só com as chaves estrangeiras e usar elas como chave primária composta

2023-07-04 00:20 UTC, lia-dias commented on prisma/migrations/20230630204300_init/migration.sql
> +    "quantidade_produto" INTEGER NOT NULL,
Não sei se é uma boa opção. A gente não colocou ainda, mas cada produto no pedido é único, ele pode ter acréscimos ou observações, ter uma 'quantidade' viola um pouco a questão de ser uma Entidade no DDD

2023-07-04 00:20 UTC, lia-dias commented on prisma/migrations/20230630204300_init/migration.sql
> +CREATE TABLE "ProdutoPedido" (
Senti falta do preço nessa tabela. É muito importante porque o preço faz parte do produto no pedido, se o preço mudar amanhã ou depois, é importante registrar o preço que foi pago hoje

2023-07-04 00:20 UTC, lia-dias commented on prisma/migrations/20230630204300_init/migration.sql
> +    "codigo" SERIAL NOT NULL,
Resolvido na próxima migration 😸

2023-07-04 00:20 UTC, lia-dias commented on prisma/schema.prisma
> +// This is your Prisma schema file,
Nesse arquivo entram as mesmas observações que foram feitas no migration

2023-07-04 00:40 UTC, sandroramone commented on prisma/migrations/20230630204300_init/migration.sql
> +    "quantidade_produto" INTEGER NOT NULL,
boa, nem pensei nisso dos acréscimos quando estava olhando.

2023-07-04 00:50 UTC, sandroramone commented on prisma/migrations/20230630204300_init/migration.sql
> +    "codigo" SERIAL NOT NULL,
@m-dantas conversamos e vimos que devido cada produto ser único no pedido devido aos acréscimos precisamos manter na verdade o código do produto pedido, ai mantemos as chaves estrangeiras como referencia mesmo, ai no caso então seria adicionar os acréscimos no lugar de quantidade.

2023-07-06 18:13 UTC, wensch approved these changes

2023-07-08 15:59 UTC, lia-dias approved these changes

2023-07-08 16:11 UTC, sandroramone approved these changes

2023-07-08 16:12 UTC, merged