Feat/cadastro cliente
PosFiap/tech_challenge pull request #8
Opened 2023-07-01 21:25 UTC by wensch

2023-07-03 00:08 UTC, m-dantas approved these changes

2023-07-04 00:56 UTC, lia-dias requested changes
Tem bastante coisa do Prisma aqui, mas eu foquei a atenção nos adapters e no módulo. Deixei alguns comentários sobre validação e responsabilidade dos componentes.

2023-07-04 00:56 UTC, lia-dias commented on src/adapter/persistence/ClienteRepository.ts
> +          return { menssagem: 'Usuário já registrado'}
Aqui a gente acaba dando um pouco de responsabilidade que a calsse não teria. A gente pode até colocar uma mensagem de erro, mas o ideal seria lançar a excessão e tratá-la onde foi chamada. Mesmo que seja retornado algo, quem deve manipular essa resposta é quem chamou, da forma que está aqui o Repository tá retornando um erro direto para a camada do express, se trocar esse adapter o controller e o express nunca vão saber retornar um erro, violamos a resposabilidade única aqui.

2023-07-04 00:56 UTC, lia-dias commented on src/adapter/controller/ClienteAdapter.ts
>  export class ClienteAdapter {
Senti falta de tratar as excessões aqui no controller, se vier uma excessão debaixo, está lançando diretamente para o express

2023-07-04 00:56 UTC, lia-dias commented on src/config/express/cliente.ts
> +router.post('/', async (req, res) => {
Podemos fazer as tratativas nos métodos do express para os outros valores. Caso já exista aqui no create, caso não exista no delete, etc

2023-07-04 00:56 UTC, lia-dias commented on src/modules/cliente/ClienteService.ts
> +export class ClienteService implements IRegistraClienteUseCase, IAtualizaClienteUseCase, IListaClienteUseCase, IDeletaClienteUseCase, IListaClienteCPFUseCase {
Aqui no módulo é onde nosso dado entra e a gente valida eles. Então o DTO que veio é real? O CPF não tá nulo ou é um número? Etc. Inclusive o DTO pode ter os próprios meios de validação.

2023-07-04 00:56 UTC, lia-dias commented on src/modules/cliente/dto/ClienteDTO.ts
> +    codigo?: number,
Comentei no outro PR

2023-07-04 00:56 UTC, lia-dias commented on src/adapter/persistence/ClienteRepository.ts
> +          return { menssagem: 'Usuário já registrado'}
Uma opção até é melhorar o ErroDTO e ele ter um enum ou algo assim indicando como lidar com a resposta.

2023-07-04 00:56 UTC, lia-dias commented on src/modules/cliente/ports/IRegistraClienteUseCase.ts
> +    registraCliente(cliente: ClienteDTO, clienteRepository: IClienteRepository): Promise<ClienteRegistryDTO | ErrorDTO>
Comentei sobre o ErrorDTO mais acima, se fizer sentido, vale adicionar esse tipo de retorno em todos os métodos da interface

2023-07-08 16:21 UTC, lia-dias approved these changes

2023-07-09 19:36 UTC, closed without merging